[package]
name = "dkls23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
k256 = { version = "0.13.1", features = ["serde"] }
bitcoin_hashes = "0.12.0"
sha3 = "0.10.8"
rand = "0.8.5"
hex = "0.4.3"
serde = { version = "1.0.188", features = ["derive"] }