name: Rust Test

on: [push, pull_request]

jobs:
  test:
    name: Run cargo test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustc, cargo, llvm-tools-preview
      - name: Install C compiler
        run: sudo apt-get install lld lldb clang -y
      - name: Configure to use LLVM linker
        run: echo "[build]" >> ~/.cargo/config && echo "rustflags = [\"-C\", \"link-arg=-fuse-ld=lld\"]" >> ~/.cargo/config
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
