# The configs for this spell check can be find at /.github/actions/spelling/
name: Spell checking
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  spelling:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check-spelling
        uses: check-spelling/check-spelling@v0.0.22
        with:
          dictionary_source_prefixes: '
            {
              "cspell_latest": "https://raw.githubusercontent.com/check-spelling/cspell-dicts/latest/dictionaries/"
            }'
          # Extra dictionaries to verify words
          extra_dictionaries:
            cspell_latest:public-licenses/src/generated/public-licenses.txt
            cspell_latest:cryptocurrencies/cryptocurrencies.txt
            cspell_latest:software-terms/src/network-protocols.txt
            cspell_latest:software-terms/src/software-terms.txt
            cspell_latest:bash/src/bash-words.txt
            cspell_latest:filetypes/filetypes.txt
            cspell_latest:fonts/fonts.txt
            cspell_latest:fullstack/src/fullstack.txt
            cspell_latest:rust/src/rust.txt
            cspell_latest:typescript/src/typescript.txt
          experimental_apply_changes_via_bot: 1
          check_file_names: 1
          suppress_push_for_open_pull_request: ${{ github.actor != 'dependabot[bot]' && 1 }}
