# The configs for this spell check can be find at /.github/actions/spelling/
name: Spell checking
on:
  push:
    branches: [main, dev]
  pull_request_target:
    branches: [main, dev]
    types:
      - 'opened'
      - 'reopened'
      - 'synchronize'

permissions: {}

jobs:
    spelling:
        name: Spell checking
        permissions:
          contents: read
          pull-requests: read
          actions: read
        runs-on: ubuntu-latest
        if: ${{ (contains(github.event_name, 'pull_request') && github.event.pull_request.state == 'open') || github.event_name == 'push' }}
        steps:
            - name: check-spelling
              uses: check-spelling/check-spelling@c635c2f3f714eec2fcf27b643a1919b9a811ef2e # v0.0.25
              with:
                  config: .github/actions/spelling
                  checkout: true
                  check_file_names: 1
                  disable_checks: noisy-file
                  post_comment: 0
                  extra_dictionaries: cspell:public-licenses/src/generated/public-licenses.txt
                      cspell:cryptocurrencies/cryptocurrencies.txt
                      cspell:software-terms/dict/networkingTerms.txt
                      cspell:software-terms/dict/softwareTerms.txt
                      cspell:bash/dict/bash-words.txt
                      cspell:filetypes/filetypes.txt
                      cspell:fonts/fonts.txt
                      cspell:fullstack/dict/fullstack.txt
                      cspell:rust/dict/rust.txt
                      cspell:typescript/dict/typescript.txt
                      cspell:sql/src/sql.txt
                      cspell:pt_BR/src/hunspell/index.dic
                      cspell:pt_BR/src/hunspell/index.aff
                      cspell:npm/dict/npm.txt
                      cspell:node/dict/node.txt
                      cspell:docker/src/docker-words.txt
