# The configs for this spell check can be find at /.github/actions/spelling
name: Spell checking
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  spelling:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check-spelling
        uses: check-spelling/check-spelling@main
        with:
          # Extra dictionaries to verify words
          extra_dictionaries:
            cspell:public-licenses/src/generated/public-licenses.txt
            cspell:cryptocurrencies/cryptocurrencies.txt
            cspell:software-terms/src/computing-acronyms.txt
            cspell:software-terms/src/network-protocols.txt
            cspell:software-terms/src/software-terms.txt
            cspell:bash/bash-words.txt
            cspell:filetypes/filetypes.txt
            cspell:fonts/fonts.txt
            cspell:fullstack/dict/fullstack.txt
            cspell:rust/dict/rust.txt
            cspell:typescript/dict/typescript.txt
          experimental_apply_changes_via_bot: 1
          check_file_names: 1
